#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")

#@ data.values.registry.server or assert.fail("missing registry.server")
#@ data.values.registry.repository or assert.fail("missing registry.repository")
---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: tekton-supply-chain
spec:
  selectorMatchExpressions:
    - key: 'apps.tanzu.vmware.com/workload-type'
      operator: In
      values: 
      - tekton

  params:
    - name: maven_repository_url
      value: #@ data.values.maven.repository.url
    #@ if/end data.values.maven.repository.secret_name:
    - name: maven_repository_secret_name
      value: #@ data.values.maven.repository.secret_name

    - name: gitops_branch
      default: #@ data.values.gitops.branch
    - name: gitops_user_name
      default: #@ data.values.gitops.username
    - name: gitops_user_email
      default: #@ data.values.gitops.email
    - name: gitops_commit_message
      default: #@ data.values.gitops.commit_message
    - name: gitops_ssh_secret
      default: #@ data.values.gitops.ssh_secret
    #@ if/end data.values.gitops.repository_prefix:
    - name: gitops_repository_prefix
      default: #@ data.values.gitops.repository_prefix
    #@ if/end data.values.gitops.server_address:
    - name: gitops_server_address
      default: #@ data.values.gitops.server_address
    #@ if/end data.values.gitops.repository_owner:
    - name: gitops_repository_owner
      default: #@ data.values.gitops.repository_owner
    #@ if/end data.values.gitops.repository_name:
    - name: gitops_repository_name
      default: #@ data.values.gitops.repository_name
    #@ if/end data.values.gitops.pull_request.server_kind:
    - name: gitops_server_kind
      default: #@ data.values.gitops.pull_request.server_kind
    #@ if/end "commit_branch" in data.values.gitops.pull_request:
    - name: gitops_commit_branch
      default: #@ data.values.gitops.pull_request.commit_branch
    #@ if/end data.values.gitops.pull_request.pull_request_title:
    - name: gitops_pull_request_title
      default: #@ data.values.gitops.pull_request.pull_request_title
    #@ if/end data.values.gitops.pull_request.pull_request_body:
    - name: gitops_pull_request_body
      default: #@ data.values.gitops.pull_request.pull_request_body

  resources:
  - name: source-provider
    templateRef:
      kind: ClusterSourceTemplate
      name: source-template
    params:
      - name: serviceAccount
        default: #@ data.values.service_account
      - name: gitImplementation
        value: #@ data.values.git_implementation

  - name: source-tester
    templateRef:
      kind: ClusterSourceTemplate
      name: testing-pipeline
    sources:
    - resource: source-provider
      name: source


          
  - name: image-provider
    templateRef:
      kind: ClusterImageTemplate
      name: kpack-template
    params:
      - name: serviceAccount
        default: #@ data.values.service_account
      - name: registry
        value: #@ data.values.registry
      - name: clusterBuilder
        default: #@ data.values.cluster_builder
      - name: dockerfile
        default: ./Dockerfile
      - name: docker_build_context
        default: ./
      - name: docker_build_extra_args
        default: []
    sources:


      - resource: source-tester
        name: source


          
  - name: config-provider
    templateRef:
      kind: ClusterConfigTemplate
      name: convention-template
    params:
      - name: serviceAccount
        default: #@ data.values.service_account
    images:

    - resource: image-provider
      name: image

  - name: app-config
    templateRef:
      kind: ClusterConfigTemplate
      name: tekton
    configs:
      - resource: config-provider
        name: config

  - name: service-bindings
    templateRef:
      kind: ClusterConfigTemplate
      name: service-bindings
    configs:
      - resource: app-config
        name: app_def

  - name: api-descriptors
    templateRef:
      kind: ClusterConfigTemplate
      name: api-descriptors
    configs:
      - resource: service-bindings
        name: app_def

  - name: config-writer
    templateRef:
      kind: ClusterTemplate
      name: config-writer-and-pull-requester-template
    params:
      - name: serviceAccount
        default: #@ data.values.service_account
      - name: registry
        value: #@ data.values.registry
    configs:
      - resource: api-descriptors
        name: config

  - name: deliverable
    templateRef:
      kind: ClusterTemplate
      name: deliverable-template
    params:
      - name: registry
        value: #@ data.values.registry


